### ISSUE TITLE
SCRIPT ERROR: @ps-adminmenu/client/data.lua:68: bad argument #1 to 'for iterator' (table expected, got nil)

### ISSUE THREAD

**Issue by polaflex** [Project-Sloth/ps-adminmenu#100]
![image](https://github.com/Project-Sloth/ps-adminmenu/assets/22807083/016b4781-1594-4bc9-b3d8-de4d8230a720)
This is what appears for me when installing ps-adminmenu. Followed instructions correctly.

Main Issue: does not load anything within the admin menu when open as shown:
![image](https://github.com/Project-Sloth/ps-adminmenu/assets/22807083/c796b132-33a3-43f9-80e9-db9138a2d39c)

Inside data.lua
![image](https://github.com/Project-Sloth/ps-adminmenu/assets/22807083/3b634435-5847-454c-bfe7-3104b9bf1574)

**Comment by Duffco1** [comment]
what was the issue with this im having same problem
