### ISSUE TITLE
Is it possible to add the Arabic language?

### ISSUE THREAD

**Issue by zero7even** [Project-Sloth/ps-adminmenu#112]
Is it possible to add the Arabic language?

  Or at least give me the location of the language files and I will try to translate it

**Comment by MonkeyWhisper** [comment]
You do it.

**Comment by zero7even** [comment]
[ar.json](https://github.com/Project-Sloth/ps-adminmenu/files/14912849/ar.json)
I just found this file and translated it using Google Translate
But I could not find the admin menu file to translate
where can I find him?
![2](https://github.com/Project-Sloth/ps-adminmenu/assets/109524760/9a855385-6e7b-4edd-a5fe-190335bcc1be)
