### ISSUE TITLE
[Feature Request] Delete Character

### ISSUE THREAD

**Issue by Voidrunner42** [Project-Sloth/ps-adminmenu#114]
**Features**
Delete character
Delete offline character

**Explanation**

A way to delete a character, of a player either for use when a character kill happens or when a player has cheated or gained access to unwanted stuff. Could be implemented really easy using simple SQL strings like.

Source (Qb-characterkill)
`                    exports.oxmysql:execute('DELETE FROM players WHERE citizenid = ?', { citizenid })
                    exports.oxmysql:execute('DELETE FROM player_vehicles WHERE citizenid = ?', { citizenid })
                    exports.oxmysql:execute('DELETE FROM player_outfits WHERE citizenid = ?', { citizenid })
                    exports.oxmysql:execute('DELETE FROM player_houses WHERE citizenid = ?', { citizenid })
                    exports.oxmysql:execute('DELETE FROM player_contacts WHERE citizenid =?', { citizenid })
                    exports.oxmysql:execute('DELETE FROM playerskins WHERE citizenid =?', { citizenid })`

**Comment by MonkeyWhisper** [comment]
Okay, go ahead and do it. Send us the PR once completed.
