### ISSUE TITLE
admin menu error

### ISSUE THREAD

**Issue by ToKaAssassin** [Project-Sloth/ps-adminmenu#116]
**Describe the bug**
/admin in my server to pop up admin menu. menu shows up but with no buttons or tags of any sorts

**To Reproduce**

**Screenshots**
![Screenshot 2024-06-12 110233](https://github.com/Project-Sloth/ps-adminmenu/assets/154643298/f0393918-8198-4ba2-80eb-67fdb9c9bb9f)

**Additional context**

**Comment by xFutte** [comment]
The value you are trying to loop over (the table) doesn't contain any values.

**Comment by ToKaAssassin** [comment]
how would i fix it?
