### ISSUE TITLE
Give Item function in menu doesnt get items from ox_inventory

### ISSUE THREAD

**Issue by Xerodar** [Project-Sloth/ps-adminmenu#119]
**Describe the bug**

Hello, in your client/data.lua code it only gets items from qb-core/shared/items.lua i have more registered items in ox_inventory than qb-core/shared/items.lua and this function idk how only get those items...
```lua
local function GetItems()
    local items = {}
    local ItemsData = QBCore.Shared.Items

    if Config.Inventory == "ox_inventory" then
        ItemsData = exports.ox_inventory:Items()
    end

    for name, v in pairs(ItemsData) do
        items[#items + 1] = { label = v.label, value = name }
    end

    return items
end
```
i also tried with this:
```lua
local function GetItems()
    local items = {}
    ItemsData = exports.ox_inventory:Items()

    for name, v in pairs(ItemsData) do
        items[#items + 1] = { label = v.label, value = name }
    end

    return items
end
```

**Comment by Xerodar** [comment]
also i tried to combine with this but it doesnt work pretty well..
https://prnt.sc/zak5cExrCHCU

**Comment by xFutte** [comment]
Just smack all of the items into the itemData table. Otherwise, move the items from one to the other to have it collectively.
