### ISSUE TITLE
You are not Admin or God

### ISSUE THREAD

**Issue by R0p-1** [Project-Sloth/ps-adminmenu#122]
**Describe the bug**
If i try to open the admin menu with command or keybind it will send a notify that is writes this: "You are not Admin or God", but im admin 
on the server so idk what is the problem.

**To Reproduce**
1. /admin
2. PgDn keybind
3. See error notification

**Screenshots**
![image](https://github.com/user-attachments/assets/669e9eac-9bf5-434d-8da7-6ba299b8123d)
![kép_2024-08-03_132509907](https://github.com/user-attachments/assets/1fc82132-c569-494d-b3b0-4cf6e085a05d)

**Additional context**

**Comment by R0p-1** [comment]
You not really completed the issue but thanks :)!

**Comment by MonkeyWhisper** [comment]
> You not really completed the issue but thanks :)!

You not really read but thanks :)!
