### ISSUE TITLE
No server announcement 

### ISSUE THREAD

**Issue by lucaskerim** [Project-Sloth/ps-adminmenu#124]
I have scrolled through all the code and theres no server announcement menu button or command at all

Even though it says you guys do maybe haven't released yet?

**Comment by lucaskerim** [comment]
????? why was this closed why advertise something and not have it

**Comment by MonkeyWhisper** [comment]
> ????? why was this closed why advertise something and not have it

Fuck off. It's a free open source script. If you want it, make it yourself.
