### ISSUE TITLE
Infinity toogle IDs

### ISSUE THREAD

**Issue by Lifad4g** [Project-Sloth/ps-adminmenu#17]
**Describe the bug**
When server is using infinity mode if a player goes far away. And comes back IDs are messed up. Because its not getting the old server id

**To Reproduce**
Find a friend toogle ids.
You get corrects IDs.
Teleport to far away. 
Then come back to old location.

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://cdn.discordapp.com/attachments/858609933259112458/1158677631206707281/image.png?ex=651d1e22&is=651bcca2&hm=26675a33362c305647a9cffc7ac2ad258ffd57e33f65e2e4a9426f589a1069b0&)
https://cdn.discordapp.com/attachments/858609933259112458/1158677744146718781/image.png?ex=651d1e3d&is=651bccbd&hm=f2856c917041cc82cd237c6e504dd70e2253124444d5d82b4fb07f4d53ef1242&

**Additional context**

**Comment by MonkeyWhisper** [comment]
Read the README.
