### ISSUE TITLE
Blips on infinity

### ISSUE THREAD

**Issue by Lifad4g** [Project-Sloth/ps-adminmenu#18]
**Describe the bug**
When blips are toggled on you can only see players on your infinity Radius.

**To Reproduce**
Toogle blips.
Get move away from the player or players
If players are close to you you can see their blips without any issues but if they leave the infinity radius blip disappears.

**Screenshots**
![image](https://github.com/Project-Sloth/ps-adminmenu/assets/38146916/05a9f614-dc20-47f0-963d-d9f493592fb2)
https://cdn.discordapp.com/attachments/858609933259112458/1158678166446014515/image.png?ex=651d1ea2&is=651bcd22&hm=4678b962862b7b9db951c959b5fc02da38a71685fd3ea3b89e65e71010f8e579&

**Additional context**

**Comment by MonkeyWhisper** [comment]
Read the README.
