### ISSUE TITLE
Staff Chat formatting and borders

### ISSUE THREAD

**Issue by DooubleTap** [Project-Sloth/ps-adminmenu#28]
The bug happens when the staff chat window is filled.

**To Reproduce**
1. Go in the staff chat
2. spam the chat or just have a normal conversation with the staff
3. it breaks

**Screenshots**
![image](https://github.com/Project-Sloth/ps-adminmenu/assets/3772136/8bb15989-2ea1-4d81-9ddd-095faf278b4d)

**Additional context**
I could add more context on demand. If possible, it would be neat if the new messages would feed from the bottom, like in a regular chat window on any major platform. 

Awesome script btw. 10/10

**Comment by MoneSuper** [comment]
Possible solution is add a scroll bar after certain number of texts
