### ISSUE TITLE
Coords not showing when doing /coords or using admin menu to toggle coords

### ISSUE THREAD

**Issue by Blazono** [Project-Sloth/ps-adminmenu#32]
Coords not showing when doing /coords or using admin menu to toggle coords

1. Go to Admin Menu, Search coords then try and toggle them
2. OR type /coords and check F8

**Screenshots**
https://gyazo.com/533975573a3128d1d0e89872b38309c6

**Comment by R3dNeckG** [comment]
Can confirm.
