### ISSUE TITLE
Text description positioning.

### ISSUE THREAD

**Issue by UnMut4d** [Project-Sloth/ps-adminmenu#33]
**Describe the bug**
Text description positioning.

**To Reproduce**
hover the mouse over the icon.

**Screenshots**
![image](https://github.com/Project-Sloth/ps-adminmenu/assets/87404229/013fe209-95f2-44ad-a500-bad35480f19b)
![image](https://github.com/Project-Sloth/ps-adminmenu/assets/87404229/d47b4943-4ed8-418e-bf65-52494391858b)
![image](https://github.com/Project-Sloth/ps-adminmenu/assets/87404229/69527c40-7202-4342-bdec-95153038c8c8)
![image](https://github.com/Project-Sloth/ps-adminmenu/assets/87404229/2e5359bd-03a2-46c8-b456-26e559933603)
![image](https://github.com/Project-Sloth/ps-adminmenu/assets/87404229/633e787f-6c6a-4a81-be58-392b3cbf955b)

**Comment by MonkeyWhisper** [comment]
This is fine, if you want it better, send a PR to fix.
