### ISSUE TITLE
THE MENU FREEZED WHEN CLICK ON PLAYERS NAME !!!!

### ISSUE THREAD

**Issue by Flash-0P** [Project-Sloth/ps-adminmenu#39]
The bug happens when we got players and click on players name the menu got freez and it does not close

this bug happens with my friends and me

To Reproduce

Go in the player
click on the players name
it breaks
and it does not close

![image](https://github.com/Project-Sloth/ps-adminmenu/assets/128111282/e2e09321-a016-458d-86f6-beb777aa67b5)

**Comment by MRKILLER-37** [comment]
> The bug happens when we got players and click on players name the menu got freez and it does not close
> 
> this bug happens with my friends and me
> 
> To Reproduce Steps to reproduce the behavior:
> 
> Go in the player click on the players name it breaks and it does not close
> 
> ![image](https://user-images.githubusercontent.com/128111282/274908249-e2e09321-a016-458d-86f6-beb777aa67b5.png)

**Comment by MonkeyWhisper** [comment]
Did not reproduce.
