### ISSUE TITLE
Ban Reason Issue

### ISSUE THREAD

**Issue by LifeCore-Development** [Project-Sloth/ps-adminmenu#68]
**Describe the bug**
When banning a user from the players tab, the reason submitted is no matter what you put in their userid, when banning through the functions tab it functions fine.

**Comment by LifeCore-Development** [comment]
https://i.gyazo.com/cfc8630751b8394a4d7d1c8c0760759e.png

Was looking here and it seems the reason is set to duration value. Not sure, as idk how to compile svelte to test my theory

**Comment by LifeCore-Development** [comment]
same thing happens when kicking from the profile page.

**Comment by LeSiiN** [comment]
Yeah thats was the issue, fixed it.
Im about to do some fixes rn

**Comment by LeSiiN** [comment]
https://github.com/Project-Sloth/ps-adminmenu/pull/82
