### ISSUE TITLE
Forever infinite ammo bug

### ISSUE THREAD

**Issue by jaylac2000** [Project-Sloth/ps-adminmenu#70]
**Describe the bug**
enabling infinite ammo / disable has no notify messages... also when you enable it, it gets stuck on that gun through restarts

**To Reproduce**

**Screenshots**

**Additional context**

**Comment by xFutte** [comment]
@jaylac2000 Please add a better description and change the title of the issue. This description doesn't tell anyone much about the issue.

**Comment by jaylac2000** [comment]
> .

Literally... pull a gun. enable infinite ammo it's forever enabled on the gun even if you disable infinite ammo. Even sticks through server restarts

**Comment by Scones91** [comment]
I can confirm, same issue here

**Comment by MorphineClinic** [comment]
thats how its supposed to be...

if you set infinite ammo on a gun and shoot it, itll change its ammo to -1 (inf)

you can reset it by using /setammo <ammo>

**Comment by timothysahakian** [comment]
/setammo does not reset it 

![Image](https://github.com/user-attachments/assets/3b159be8-b4e4-42ca-994c-24f536a5fe59)
