### ISSUE TITLE
Player Troll Not Working

### ISSUE THREAD

**Issue by Erdenee423** [Project-Sloth/ps-adminmenu#72]
**Describe the bug**
when select player in troll getting this error in screenshot and frozend the whole script not working anything

**To Reproduce**
1. Go to 'Player'
2. Click on 'some player'
4. when clicks it then nothing show and script fully get frozen

**Screenshots**
https://prnt.sc/m3O7PX5KY7S8 this is screenshot the error in f8

**Additional context**

**Comment by LeSiiN** [comment]
we need a more specific description

**Comment by nvanoirschot** [comment]
I have the same error: 
![error](https://github.com/Project-Sloth/ps-adminmenu/assets/151923176/ad0b8145-bd4a-42ec-ab78-14cd339234a7)
