### ISSUE TITLE
Permissions dont work

### ISSUE THREAD

**Issue by LordSokaris** [Project-Sloth/ps-adminmenu#76]
**Describe the bug**
When I try to perform some action with the admin menu, I cannot execute it because it always tells me that I am not an admin or god, but I have permissions from the server.cfg as administrator and I have already changed all the permissions of the admin menu to admin

**To Reproduce**
1. Go to 'any option'
2. Click on 'confirm'
4. Your are not a admin or god

**Screenshots**

![image](https://github.com/Project-Sloth/ps-adminmenu/assets/102775818/9fc4d9f5-05b9-4387-83ab-d2a173c6f615)

permissions

![image](https://github.com/Project-Sloth/ps-adminmenu/assets/102775818/c99f49af-830c-4dfd-9241-77739cc0c5bf)

**Additional context**
The problem is with any option on the menu.

**Comment by Fessel-dev** [comment]
I am having the same problem. Was the fix discovered?
