### ISSUE TITLE
Ps-adminmenu after update v1.1.0

### ISSUE THREAD

**Issue by enesrevenge** [Project-Sloth/ps-adminmenu#80]
**Describe the bug**
When I updated the ps-adminmenu script to v1.1
 1st error: 
 the noclip button was broken.
  2nd error:
  When I press the quick actions / "watch player" button in the players section, the player gets revived.

**Screenshots**
![image](https://github.com/Project-Sloth/ps-adminmenu/assets/121297265/07aefe9f-d32e-4c11-ae5e-fa84b572af09)

**Comment by enesrevenge** [comment]
and and and copy coords doesn't work it's bug

**Comment by MonkeyWhisper** [comment]
Those are all working fine. I tested msyelf.
