### ISSUE TITLE
Copy Coords Bug

### ISSUE THREAD

**Issue by FrankkGpK** [Project-Sloth/ps-adminmenu#84]
**Describe the bug**
Copy Coord's only doing vector2 for all 4 options.

**To Reproduce**
1. Go to 'Admin Menu'
2. Click on 'Actions'
3. Scroll down to 'Copy Coords'
4. Select each option and paste to notepad, all options vec2, vec3, vec4 and heading only produce vector2.

**Screenshots**
![image](https://github.com/Project-Sloth/ps-adminmenu/assets/27672266/97292b62-d289-4689-9667-2e2b679a8cbf)

**Comment by MonkeyWhisper** [comment]
https://github.com/Project-Sloth/ps-adminmenu/pull/82
