### ISSUE TITLE
Copy Coords is not working properly.

### ISSUE THREAD

**Issue by nefariousxyz** [Project-Sloth/ps-adminmenu#85]
**Describe the bug**
"Copy Coords" is just showing vector2 coords even if i press vector 3 & 4. Screenshot below.

**Screenshots**
![image](https://github.com/Project-Sloth/ps-adminmenu/assets/65008430/d0ad054a-6886-4b01-b7dd-40d4fd9fc74e)

**Comment by LeSiiN** [comment]
got fixed
