### ISSUE TITLE
 Uncaught (in promise) SyntaxError: Unexpected end of JSON input (@ps-adminmenu/html/index.html:1)

### ISSUE THREAD

**Issue by nvanoirschot** [Project-Sloth/ps-adminmenu#88]
Unable to spawn vehicles that are already registered under a player in the adminmenu.

While it functions flawlessly in version 1.0.3 and possibly in other versions, it does not operate as intended in version 1.1.X.

**Comment by nvanoirschot** [comment]
> Unable to spawn vehicles that are already registered under a player in the adminmenu.
> 
> While it functions flawlessly in version 1.0.3 and possibly in other versions, it does not operate as intended in version 1.1.X.


The functionality is operational up to version 1.0.8, and subsequent versions (1.1.X and beyond) experience issues.

**Comment by LeSiiN** [comment]
I will check that if i got time

**Comment by PIXELR1** [comment]
![Screenshot 2024-01-01 053706](https://github.com/Project-Sloth/ps-adminmenu/assets/154515088/8c65b552-cfe2-4cf4-8580-c601abe7c56e)

![Screenshot 2024-01-01 053636](https://github.com/Project-Sloth/ps-adminmenu/assets/154515088/a6ea31d9-9406-490d-b986-281745c673ba)

my ps admin menu is not working ?


can you tell me how to fix this ?

**Comment by LeSiiN** [comment]
> ![Screenshot 2024-01-01 053706](https://private-user-images.githubusercontent.com/154515088/293523317-8c65b552-cfe2-4cf4-8580-c601abe7c56e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwNTkyMjMsIm5iZiI6MTcwNDA1ODkyMywicGF0aCI6Ii8xNTQ1MTUwODgvMjkzNTIzMzE3LThjNjViNTUyLWNmZTItNGNmNC04NTgwLWM2MDFhYmU3YzU2ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjMxMjMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIzMVQyMTQyMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hM2Y4Y2ZmOTEwNmM1YWJmMDI4ZDA1YjU2MTZmNWFiYmViMDVkNDQ1MDZiMTU0NTVhZDg4MDgxODRjYzk2YmQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.j2HZ-V8nO63gfJ-MPHjvYCRXmEUIJNk_QEPjCufQT1s)
> 
> ![Screenshot 2024-01-01 053636](https://private-user-images.githubusercontent.com/154515088/293523312-a6ea31d9-9406-490d-b986-281745c673ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwNTkyMjMsIm5iZiI6MTcwNDA1ODkyMywicGF0aCI6Ii8xNTQ1MTUwODgvMjkzNTIzMzEyLWE2ZWEzMWQ5LTk0MDYtNDkwZC1iOTg2LTI4MTc0NWM2NzNiYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjMxMjMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIzMVQyMTQyMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZDUyY2M5ZTA1ZWEzM2Y5MmMyMTdiODQ5MTc3ZjIwY2NjNWFiODhhZjFlN2YyMmYyMDM3OWFkNGM5ODRlZmM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jdlZjol0Qa3DK_AHDbKFJMBtwX5XlLEhwuM1JbRew7o)
> 
> my ps admin menu is not working ?
> 
> can you tell me how to fix this ?

Head to our Discord for support

**Comment by LeSiiN** [comment]
Got fixed
